Repository fridge-rescue/fridge-rescue-server, pull requests merged in 2024-01, with the labels that each got.

#27 신고 테이블, Entity 매핑 #5
  src/main/java/team/rescue/fridge/report/Report.java
Labels: enhancement

#26 Spring Security 초기 세팅 및 jwt 기반 인증 인가 처리
  build.gradle
  src/main/java/team/rescue/fridge/config/RedisConfig.java
  src/main/java/team/rescue/fridge/config/SecurityConfig.java
  src/main/java/team/rescue/fridge/dto/AuthMember.java
  src/main/java/team/rescue/fridge/dto/LoginDto.java
  src/main/java/team/rescue/fridge/handler/AuthenticationExceptionHandler.java
  src/main/java/team/rescue/fridge/handler/AuthorizationExceptionHandler.java
  src/main/java/team/rescue/fridge/member/MemberRepository.java
  src/main/java/team/rescue/fridge/security/JwtAuthenticationFilter.java
  src/main/java/team/rescue/fridge/security/JwtAuthorizationFilter.java
  src/main/java/team/rescue/fridge/security/JwtTokenProvider.java
  src/main/java/team/rescue/fridge/security/MemberDetailService.java
  src/main/java/team/rescue/fridge/security/RedisUtil.java
  src/main/java/team/rescue/fridge/security/dto/TokenDto.java
  src/main/java/team/rescue/fridge/security/token/JwtTokenType.java
Labels: enhancement

#46 배포
  src/main/java/team/rescue/config/SecurityConfig.java
Labels: deploy

#51 레시피 테이블에 조회수 컬럼 추가 #49
  sql/ddl.sql
  src/main/java/team/rescue/recipe/entity/Recipe.java
Labels: enhancement

#54 프로젝트 공통 예외 처리 및 공통 응답값 DTO 정의 #23
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/common/dto/ResponseDto.java
  src/main/java/team/rescue/error/GlobalExceptionHandler.java
  src/main/java/team/rescue/error/exception/.keep
  src/main/java/team/rescue/error/exception/AuthException.java
  src/main/java/team/rescue/error/exception/UserException.java
  src/main/java/team/rescue/error/exception/ValidationException.java
  src/main/java/team/rescue/error/type/.keep
  src/main/java/team/rescue/error/type/AuthError.java
  src/main/java/team/rescue/error/type/UserError.java
Labels: refact

#60 Deploy
  scripts/start.sh
Labels: deploy

#56 Email 회원가입 및 Email 인증 코드 처리 #12
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/dto/JoinDto.java
  src/main/java/team/rescue/auth/provider/JwtTokenProvider.java
  src/main/java/team/rescue/auth/provider/MailProvider.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/auth/service/OAuthService.java
  src/main/java/team/rescue/error/type/UserError.java
  src/main/java/team/rescue/fridge/entity/Fridge.java
  src/main/java/team/rescue/fridge/service/FridgeService.java
  src/main/java/team/rescue/member/dto/.keep
  src/main/java/team/rescue/member/dto/MemberDto.java
  src/main/java/team/rescue/member/entity/Member.java
  src/main/java/team/rescue/util/RandomCodeUtil.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/team/rescue/auth/controller/AuthControllerTest.java
  src/test/java/team/rescue/auth/service/AuthServiceTest.java
  src/test/java/team/rescue/mock/MockMember.java
  src/test/java/team/rescue/mock/WithMockMember.java
  src/test/java/team/rescue/mock/WithMockMemberSecurityFactory.java
  src/test/resources/application.yml
Labels: enhancement

#72 레시피 리뷰 등록, 조회 기능 구현 #1
  src/main/java/team/rescue/common/dto/ImageDto.java
  src/main/java/team/rescue/common/file/FileService.java
  src/main/java/team/rescue/config/SecurityConfig.java
  src/main/java/team/rescue/cook/repository/CookRepository.java
  src/main/java/team/rescue/error/GlobalExceptionHandler.java
  src/main/java/team/rescue/error/exception/ServiceException.java
  src/main/java/team/rescue/error/exception/UserException.java
  src/main/java/team/rescue/error/type/ReviewError.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/repository/RecipeRepository.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/entity/Review.java
  src/main/java/team/rescue/review/repository/ReviewRepository.java
  src/main/java/team/rescue/review/service/ReviewService.java
Labels: enhancement

#76 이미지 파일 S3 버킷 업로드 #16
  build.gradle
  sql/ddl.sql
  src/main/java/team/rescue/common/dto/ImageDto.java
  src/main/java/team/rescue/common/file/FileService.java
  src/main/java/team/rescue/config/AwsConfig.java
  src/main/java/team/rescue/error/GlobalExceptionHandler.java
  src/main/java/team/rescue/error/exception/ServiceException.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/entity/RecipeStep.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/.keep
  src/main/java/team/rescue/review/entity/Review.java
  src/main/java/team/rescue/util/ImageUtil.java
  src/main/java/team/rescue/util/RandomCodeUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#81 공통 응답 DTO 수정, DTO 네이밍 통일화 및 Exception 통일 #71
  src/main/java/team/rescue/aop/RequestValidAop.java
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java
  src/main/java/team/rescue/auth/handler/OAuthAuthorizationSuccessHandler.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/auth/service/OAuthService.java
  src/main/java/team/rescue/common/dto/ResponseDto.java
  src/main/java/team/rescue/error/GlobalExceptionHandler.java
  src/main/java/team/rescue/error/exception/ServiceException.java
  src/main/java/team/rescue/error/exception/UserException.java
  src/main/java/team/rescue/error/type/ReviewError.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/error/type/UserError.java
  src/main/java/team/rescue/fridge/controller/FridgeController.java
  src/main/java/team/rescue/fridge/dto/FridgeDto.java
  src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java
  src/main/java/team/rescue/fridge/service/FridgeService.java
  src/main/java/team/rescue/member/dto/MemberDto.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/.keep
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/service/ReviewService.java
  src/test/java/team/rescue/auth/controller/AuthControllerTest.java
  src/test/java/team/rescue/auth/service/AuthServiceTest.java
Labels: refact

#85 Production Deploy
  .github/workflows/db-deploy.yml
Labels: deploy

#86 Production Deploy
  .github/workflows/db-deploy.yml
Labels: deploy

#87 Create Health Check API for EB Health Checking
  src/main/java/team/rescue/HealthCheckController.java
  src/main/java/team/rescue/config/SecurityConfig.java
Labels: deploy

#89 Production Deploy
  .ebextensions/00-makeFiles.config
  .platform/nginx/nginx.conf
  src/main/resources/application-prod.yml
Labels: deploy

#90 환경 리커버리 시간 증가
  .github/workflows/db-deploy.yml
Labels: deploy

#91 환경변수 네이밍 룰 적용
  src/main/resources/application-prod.yml
Labels: deploy

#93 Deploy
  src/main/java/team/rescue/aop/ListValidation.java
  src/main/java/team/rescue/aop/RequestValidAop.java
  src/main/java/team/rescue/fridge/controller/FridgeController.java
  src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java
Labels: deploy

#94 회원 탈퇴 기능 구현 #37
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/fridge/repository/FridgeRepository.java
  src/test/java/team/rescue/auth/controller/AuthControllerTest.java
  src/test/java/team/rescue/auth/service/AuthServiceTest.java
Labels: enhancement

#96 FridgeController, FridgeService 테스트 코드 작성 #67
  src/main/java/team/rescue/fridge/controller/FridgeController.java
  src/main/java/team/rescue/fridge/service/FridgeService.java
  src/test/java/team/rescue/fridge/controller/FridgeControllerTest.java
  src/test/java/team/rescue/fridge/service/FridgeServiceTest.java
Labels: test

#102 JWT 토큰 재발급 및 유효성 에러 처리 로직 수정
  src/main/java/team/rescue/aop/RequestValidAop.java
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/common/file/FileService.java
  src/main/java/team/rescue/error/type/AuthError.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/fridge/controller/FridgeController.java
  src/main/java/team/rescue/fridge/repository/FridgeRepository.java
  src/main/java/team/rescue/fridge/service/FridgeService.java
  src/main/java/team/rescue/member/controller/MemberController.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/dto/RecipeIngredientDto.java
  src/main/java/team/rescue/recipe/dto/RecipeStepDto.java
  src/main/java/team/rescue/recipe/dto/RecipesDto.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/test/java/team/rescue/auth/controller/AuthControllerTest.java
  src/test/java/team/rescue/auth/service/AuthServiceTest.java
  src/test/java/team/rescue/fridge/controller/FridgeControllerTest.java
  src/test/java/team/rescue/fridge/service/FridgeServiceTest.java
Labels: deploy

#104 로그아웃 기능 구현 및 서버 CORS 설정 오류 수정
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/config/SecurityConfig.java
  src/test/java/team/rescue/auth/controller/AuthControllerTest.java
  src/test/java/team/rescue/auth/service/AuthServiceTest.java
Labels: deploy

#105 알림 확인 기능 구현 #40
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/notification/controller/NotificationController.java
  src/main/java/team/rescue/notification/dto/.keep
  src/main/java/team/rescue/notification/dto/NotificationDto.java
  src/main/java/team/rescue/notification/entity/Notification.java
  src/main/java/team/rescue/notification/repository/NotificationRepository.java
  src/main/java/team/rescue/notification/service/NotificationService.java
  src/test/java/team/rescue/notification/controller/NotificationControllerTest.java
  src/test/java/team/rescue/notification/service/NotificationServiceTest.java
Labels: enhancement

#106 Deploy
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/notification/controller/NotificationController.java
  src/main/java/team/rescue/notification/dto/.keep
  src/main/java/team/rescue/notification/dto/NotificationDto.java
  src/main/java/team/rescue/notification/entity/Notification.java
  src/main/java/team/rescue/notification/repository/NotificationRepository.java
  src/main/java/team/rescue/notification/service/NotificationService.java
  src/test/java/team/rescue/notification/controller/NotificationControllerTest.java
  src/test/java/team/rescue/notification/service/NotificationServiceTest.java
Labels: deploy

#109 유효성 검사 수정 및 이메일 인증 API 접근 권한 원복
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/dto/JoinDto.java
  src/main/java/team/rescue/member/dto/MemberDto.java
Labels: deploy

#113 완료된 요리 조회 기능 구현 및 회원가입 시 이름 값 받지 않도록 변경
  compose.yaml
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/dto/JoinDto.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/auth/service/OAuthService.java
  src/main/java/team/rescue/cook/dto/.keep
  src/main/java/team/rescue/cook/dto/CookDto.java
  src/main/java/team/rescue/cook/repository/CookRepository.java
  src/main/java/team/rescue/member/controller/MemberController.java
  src/main/java/team/rescue/member/dto/MemberDto.java
  src/main/java/team/rescue/member/entity/Member.java
  src/main/java/team/rescue/member/service/MemberService.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/repository/ReviewRepository.java
  src/main/resources/application-dev.yml
  src/test/java/team/rescue/auth/controller/AuthControllerTest.java
  src/test/java/team/rescue/auth/service/AuthServiceTest.java
  src/test/java/team/rescue/fridge/service/FridgeServiceTest.java
  src/test/java/team/rescue/member/controller/MemberControllerTest.java
  src/test/java/team/rescue/member/service/MemberServiceTest.java
  src/test/java/team/rescue/mock/MockMember.java
  src/test/java/team/rescue/notification/service/NotificationServiceTest.java
Labels: deploy

#118 레시피 등록, 조회 및 이메일 인증 권한 체크 하지 않도록 수정
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/common/file/FileService.java
  src/main/java/team/rescue/error/type/RecipeError.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/dto/RecipeIngredientDto.java
  src/main/java/team/rescue/recipe/dto/RecipeStepDto.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/entity/RecipeIngredient.java
  src/main/java/team/rescue/recipe/entity/RecipeStep.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
Labels: deploy

#122 특정 레시피 북마크 기능 구현 #121
  build.gradle
  src/main/java/team/rescue/aop/DistributedLock.java
  src/main/java/team/rescue/aop/LockAopAspect.java
  src/main/java/team/rescue/aop/LockManager.java
  src/main/java/team/rescue/config/RedisConfig.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/BookmarkDto.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/repository/BookmarkRepository.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/test/java/team/rescue/aop/LockAopAspectTest.java
  src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
Labels: enhancement

#123 리뷰 수정, 삭제 기능 구현 #31
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/entity/Review.java
  src/main/java/team/rescue/review/service/ReviewService.java
Labels: enhancement

#125 Deploy
  build.gradle
  src/main/java/team/rescue/aop/DistributedLock.java
  src/main/java/team/rescue/aop/LockAopAspect.java
  src/main/java/team/rescue/aop/LockManager.java
  src/main/java/team/rescue/config/RedisConfig.java
  src/main/java/team/rescue/cook/controller/CookController.java
  src/main/java/team/rescue/cook/dto/CookDto.java
  src/main/java/team/rescue/cook/service/CookService.java
  src/main/java/team/rescue/error/type/RecipeError.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java
  src/main/java/team/rescue/member/controller/MemberController.java
  src/main/java/team/rescue/member/service/MemberService.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/BookmarkDto.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/repository/.keep
  src/main/java/team/rescue/recipe/repository/BookmarkRepository.java
  src/main/java/team/rescue/recipe/repository/RecipeRepository.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/entity/Review.java
  src/main/java/team/rescue/review/service/ReviewService.java
  src/test/java/team/rescue/aop/LockAopAspectTest.java
  src/test/java/team/rescue/cook/controller/CookControllerTest.java
  src/test/java/team/rescue/cook/service/CookServiceTest.java
  src/test/java/team/rescue/member/controller/MemberControllerTest.java
  src/test/java/team/rescue/member/service/MemberServiceTest.java
  src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
Labels: deploy

#127 특정 레시피 리뷰 목록 반환 #120
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/repository/ReviewRepository.java
  src/main/java/team/rescue/review/service/ReviewService.java
  src/main/resources/application-dev.yml
Labels: enhancement

#126 신고 기능 구현 #25
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/report/controller/ReportController.java
  src/main/java/team/rescue/report/dto/.keep
  src/main/java/team/rescue/report/dto/ReportDto.java
  src/main/java/team/rescue/report/repository/.keep
  src/main/java/team/rescue/report/repository/ReportRepository.java
  src/main/java/team/rescue/report/service/ReportService.java
Labels: enhancement

#131 레시피 조회 시 리뷰 목록 조회 및 신고 기능
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/repository/RecipesRepository.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/report/controller/ReportController.java
  src/main/java/team/rescue/report/dto/.keep
  src/main/java/team/rescue/report/dto/ReportDto.java
  src/main/java/team/rescue/report/repository/.keep
  src/main/java/team/rescue/report/repository/ReportRepository.java
  src/main/java/team/rescue/report/service/ReportService.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/repository/ReviewRepository.java
  src/main/java/team/rescue/review/service/ReviewService.java
  src/main/resources/application-dev.yml
  src/test/java/team/rescue/recipe/service/RecipeServiceTest.java
Labels: deploy

#132 인증 요청값 파라미터 이름 변경 providerType -> provider
  src/main/java/team/rescue/auth/controller/AuthController.java
Labels: deploy

#139 회원 비밀번호 변경 DTO 수정 및 전체 에러 핸들링 메서드 추가
  src/main/java/team/rescue/error/GlobalExceptionHandler.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/member/dto/MemberDto.java
  src/main/java/team/rescue/member/service/MemberService.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/dto/RecipeStepDto.java
  src/main/java/team/rescue/recipe/entity/RecipeStep.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/test/java/team/rescue/member/controller/MemberControllerTest.java
  src/test/java/team/rescue/member/service/MemberServiceTest.java
  src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
  src/test/java/team/rescue/recipe/service/RecipeServiceTest.java
Labels: deploy

#140 JWT 토큰 응답값 변경 #135
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/dto/LoginDto.java
  src/main/java/team/rescue/auth/dto/TokenDto.java
  src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java
  src/main/java/team/rescue/auth/handler/OAuthAuthorizationSuccessHandler.java
Labels: refact

#141 JWT Token 관련 응답값 변경
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/dto/LoginDto.java
  src/main/java/team/rescue/auth/dto/TokenDto.java
  src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java
  src/main/java/team/rescue/auth/handler/OAuthAuthorizationSuccessHandler.java
Labels: deploy

#142 로그 레벨 변경
  src/main/resources/application-prod.yml
Labels: deploy

#143 레시피 생성 로그 추가
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy

#144 레시피 생성 로그 추가
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy

#147 Elasticsearch 연동 및 리뷰 생성 시각 반환
  build.gradle
  src/main/java/team/rescue/config/ElasticsearchConfig.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: deploy

#154 재료 등록 자동완성 기능 구현 및 유통기한 날짜 입력 시 시간 데이터 제외
  src/main/java/team/rescue/config/RedisConfig.java
  src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java
  src/main/java/team/rescue/fridge/entity/FridgeIngredient.java
  src/main/java/team/rescue/fridge/repository/FridgeIngredientRepository.java
  src/main/java/team/rescue/recipe/repository/RecipeIngredientRepository.java
  src/main/java/team/rescue/search/controller/SearchController.java
  src/main/java/team/rescue/search/service/SearchService.java
  src/main/resources/application-test.yml
  src/test/java/team/rescue/fridge/controller/FridgeControllerTest.java
Labels: deploy

#163 토큰 재발급 로직 수정, 재료 일괄 수정 네이밍 변경
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/filter/JwtAuthorizationFilter.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/cook/dto/CookDto.java
  src/main/java/team/rescue/cook/service/CookService.java
  src/main/java/team/rescue/fridge/controller/FridgeController.java
  src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java
  src/main/java/team/rescue/fridge/service/FridgeService.java
  src/main/java/team/rescue/search/controller/SearchController.java
  src/test/java/team/rescue/cook/controller/CookControllerTest.java
  src/test/java/team/rescue/cook/service/CookServiceTest.java
Labels: deploy

#170 검색 기능 관련 컨트롤러, 리포지토리 일부 구현 및 레시피 DTO 변경점 반영
  src/main/java/team/rescue/aop/RequestValidAop.java
  src/main/java/team/rescue/config/ElasticsearchConfig.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/dto/RecipeIngredientDto.java
  src/main/java/team/rescue/recipe/dto/RecipeStepDto.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/review/repository/.keep
  src/main/java/team/rescue/search/controller/SearchController.java
  src/main/java/team/rescue/search/dto/RecipeSearchDto.java
  src/main/java/team/rescue/search/entity/RecipeDoc.java
  src/main/java/team/rescue/search/repository/RecipeSearchRepository.java
  src/main/java/team/rescue/search/service/RecipeSearchService.java
  src/main/java/team/rescue/search/type/SortType.java
  src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
  src/test/java/team/rescue/recipe/service/RecipeServiceTest.java
Labels: enhancement

#171 deploy
  src/main/java/team/rescue/aop/RequestValidAop.java
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/config/ElasticsearchConfig.java
  src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/dto/RecipeIngredientDto.java
  src/main/java/team/rescue/recipe/dto/RecipeStepDto.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/review/controller/ReviewController.java
  src/main/java/team/rescue/review/dto/ReviewDto.java
  src/main/java/team/rescue/review/repository/.keep
  src/main/java/team/rescue/review/service/ReviewService.java
  src/main/java/team/rescue/search/controller/SearchController.java
  src/main/java/team/rescue/search/dto/RecipeSearchDto.java
  src/main/java/team/rescue/search/entity/RecipeDoc.java
  src/main/java/team/rescue/search/repository/RecipeSearchRepository.java
  src/main/java/team/rescue/search/service/RecipeSearchService.java
  src/main/java/team/rescue/search/type/SortType.java
  src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
  src/test/java/team/rescue/recipe/service/RecipeServiceTest.java
Labels: deploy

#173 레시피 스텝 이미지 등록 첫 번째 이미지만 저장하지 않도록 수정
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy

#176 이메일 인증 로그인 이전에도 처리할 수 있도록 수정
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/dto/JoinDto.java
Labels: deploy

#178 레시피 수정 DTO 반영
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy

#181 deploy
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/member/dto/MemberDto.java
Labels: deploy

#184 deploy
  src/main/java/team/rescue/review/entity/Review.java
  src/main/java/team/rescue/review/service/ReviewService.java
  src/main/java/team/rescue/search/controller/SearchController.java
  src/main/java/team/rescue/search/entity/RecipeDoc.java
  src/main/java/team/rescue/search/repository/RecipeSearchRepository.java
  src/main/java/team/rescue/search/service/RecipeSearchService.java
  src/main/java/team/rescue/search/type/SortType.java
Labels: deploy

#190 최신 레시피 조회, 냉장고 재료 기반 레시피 조회 기능 구현
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/repository/RecipeRepository.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/review/service/ReviewService.java
  src/main/java/team/rescue/search/controller/SearchController.java
  src/main/java/team/rescue/search/repository/RecipeSearchRepository.java
  src/main/java/team/rescue/search/service/RecipeSearchService.java
Labels: deploy

#192 레시피 상세 조회 시 북마크 여부 포함하도록 변경 #191
  src/main/java/team/rescue/member/controller/MemberController.java
  src/main/java/team/rescue/member/service/MemberService.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/repository/BookmarkRepository.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: refact

#194 레시피 상세 페이지 북마크 여부 포함, 키워드 기반 검색 기능 구현
  src/main/java/team/rescue/member/controller/MemberController.java
  src/main/java/team/rescue/member/dto/MemberDto.java
  src/main/java/team/rescue/member/service/MemberService.java
  src/main/java/team/rescue/notification/entity/NotificationProperty.java
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/repository/BookmarkRepository.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/search/controller/SearchController.java
  src/main/java/team/rescue/search/entity/RecipeDoc.java
  src/main/java/team/rescue/search/repository/RecipeSearchRepository.java
  src/main/java/team/rescue/search/service/RecipeSearchService.java
  src/main/java/team/rescue/search/type/SortType.java
Labels: deploy

#196 이미 신고한 레시피를 다시 신고하는 경우 409 에러 반환 #195
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/report/repository/ReportRepository.java
  src/main/java/team/rescue/report/service/ReportService.java
Labels: enhancement

#197 이미 신고한 레시피를 다시 신고하는 경우 409 에러 반환
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/report/repository/ReportRepository.java
  src/main/java/team/rescue/report/service/ReportService.java
Labels: deploy

#198 전체 레시피 개수 반환
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/repository/RecipeRepository.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy

#201 로그인 유저 레시피 조회 시 북마크 여부 반환하도록 변경
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy

#205 회원 탈퇴 기능 수정 및 최신 레시피, 인기 레시피 조회 프록시 에러 수정
  src/main/java/team/rescue/auth/controller/AuthController.java
  src/main/java/team/rescue/auth/service/AuthService.java
  src/main/java/team/rescue/auth/user/PrincipalDetails.java
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/member/entity/Member.java
  src/main/java/team/rescue/member/service/MemberService.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/test/java/team/rescue/auth/controller/AuthControllerTest.java
  src/test/java/team/rescue/auth/service/AuthServiceTest.java
Labels: deploy

#210 레시피 수정, 키워드기반 검색 공백 포함하도록 수정, 레시피 관련 테이블 글자수 100 -> 200 늘림
  src/main/java/team/rescue/error/type/ServiceError.java
  src/main/java/team/rescue/recipe/dto/RecipeDto.java
  src/main/java/team/rescue/recipe/dto/RecipeStepDto.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/entity/RecipeStep.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/search/repository/RecipeSearchRepository.java
  src/main/java/team/rescue/search/service/RecipeSearchService.java
Labels: deploy

#213 유효기간 1일 남은 재료 로그인 시 알림 #41
  src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java
  src/main/java/team/rescue/config/RedisConfig.java
  src/main/java/team/rescue/config/SecurityConfig.java
  src/main/java/team/rescue/notification/RedisSubscriber.java
  src/main/java/team/rescue/notification/controller/NotificationController.java
  src/main/java/team/rescue/notification/dto/NotificationDto.java
  src/main/java/team/rescue/notification/entity/Notification.java
  src/main/java/team/rescue/notification/event/NotificationEvent.java
  src/main/java/team/rescue/notification/event/NotificationEventHandler.java
  src/main/java/team/rescue/notification/event/NotificationEventPublisher.java
  src/main/java/team/rescue/notification/repository/.keep
  src/main/java/team/rescue/notification/repository/NotificationRepository.java
  src/main/java/team/rescue/notification/repository/SseEmitterRepository.java
  src/main/java/team/rescue/notification/service/NotificationService.java
  src/main/java/team/rescue/notification/service/RedisMessageService.java
  src/main/java/team/rescue/notification/service/SseEmitterService.java
  src/main/java/team/rescue/search/entity/RecipeDoc.java
Labels: enhancement

#212 0시에 신고 개수 10개 이상인 레시피 블라인드 처리 #58
  src/main/java/team/rescue/common/schedule/report/ReportScheduler.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: enhancement

#214 유통기한 알림, 신고 레시피 is_blocked 컬럼 업데이트
  src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java
  src/main/java/team/rescue/common/schedule/report/ReportScheduler.java
  src/main/java/team/rescue/config/RedisConfig.java
  src/main/java/team/rescue/config/SecurityConfig.java
  src/main/java/team/rescue/notification/RedisSubscriber.java
  src/main/java/team/rescue/notification/controller/NotificationController.java
  src/main/java/team/rescue/notification/dto/NotificationDto.java
  src/main/java/team/rescue/notification/entity/Notification.java
  src/main/java/team/rescue/notification/event/NotificationEvent.java
  src/main/java/team/rescue/notification/event/NotificationEventHandler.java
  src/main/java/team/rescue/notification/event/NotificationEventPublisher.java
  src/main/java/team/rescue/notification/repository/.keep
  src/main/java/team/rescue/notification/repository/NotificationRepository.java
  src/main/java/team/rescue/notification/repository/SseEmitterRepository.java
  src/main/java/team/rescue/notification/service/NotificationService.java
  src/main/java/team/rescue/notification/service/RedisMessageService.java
  src/main/java/team/rescue/notification/service/SseEmitterService.java
  src/main/java/team/rescue/recipe/dto/RecipeStepDto.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/search/entity/RecipeDoc.java
Labels: deploy

#220 deploy
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy

#223 deploy
  src/main/java/team/rescue/recipe/controller/RecipeController.java
  src/main/java/team/rescue/recipe/entity/Recipe.java
  src/main/java/team/rescue/recipe/service/RecipeService.java
  src/main/java/team/rescue/review/service/ReviewService.java
Labels: deploy

#225 레시피 수정시 recipeImage required false 처리
  src/main/java/team/rescue/recipe/controller/RecipeController.java
Labels: deploy

#228 Recipe Image null 체크 수정
  src/main/java/team/rescue/recipe/service/RecipeService.java
Labels: deploy
